feat(frontend): get themeColor from cms setting
kids-reporter/kids-reporter-monorepo pull request #364
Opened 2023-11-22 04:39 UTC by howar31

2023-11-23 06:22 UTC, duidae requested changes
Mostly looking good, just some redundant fields in query & small adjustments, please have a look, thanks.

2023-11-23 06:22 UTC, duidae commented on packages/frontend/src/app/(sticky-header)/article/[slug]/article.tsx
> +  const theme = subcategory?.category?.themeColor || DEFAULT_THEME_COLOR
we defined `category` above, so could use `const theme = category?.themeColor` here

2023-11-23 06:22 UTC, duidae commented on packages/frontend/src/app/page.tsx
> +    themeColor
seems this field is not used

2023-11-23 06:22 UTC, duidae commented on packages/frontend/src/app/utils/index.ts
> +      theme: subSubcategory?.subcategory?.category?.themeColor,
we may need fallback `DEFAULT_THEME_COLOR` here in case the query is missing `themeColor` field

2023-11-23 06:22 UTC, duidae commented on packages/frontend/src/app/(sticky-header)/category/[[...path]]/page.tsx
> +    themeColor
seems this field is not used

2023-11-23 06:22 UTC, duidae commented on packages/frontend/src/app/(sticky-header)/category/[[...path]]/page.tsx
> +      themeColor
seems this field is not used

2023-11-23 06:22 UTC, duidae commented on packages/frontend/src/app/(sticky-header)/category/[[...path]]/page.tsx
> +        themeColor
seems this field is not used

2023-11-23 06:24 UTC, duidae commented on packages/frontend/src/app/(sticky-header)/category/[[...path]]/page.tsx
> +    theme = categoryData.themeColor
can we also have fallback `DEFAULT_THEME_COLOR` here?

2023-11-24 03:42 UTC, howar31 commented on packages/frontend/src/app/(sticky-header)/article/[slug]/article.tsx
> +  const theme = subcategory?.category?.themeColor || DEFAULT_THEME_COLOR
done

2023-11-24 03:42 UTC, howar31 commented on packages/frontend/src/app/(sticky-header)/category/[[...path]]/page.tsx
> +    themeColor
done

2023-11-24 03:42 UTC, howar31 commented on packages/frontend/src/app/(sticky-header)/category/[[...path]]/page.tsx
> +      themeColor
done

2023-11-24 03:42 UTC, howar31 commented on packages/frontend/src/app/(sticky-header)/category/[[...path]]/page.tsx
> +        themeColor
done

2023-11-24 03:42 UTC, howar31 commented on packages/frontend/src/app/(sticky-header)/category/[[...path]]/page.tsx
> +    theme = categoryData.themeColor
done

2023-11-24 03:42 UTC, howar31 commented on packages/frontend/src/app/page.tsx
> +    themeColor
done

2023-11-24 03:42 UTC, howar31 commented on packages/frontend/src/app/utils/index.ts
> +      theme: subSubcategory?.subcategory?.category?.themeColor,
done

2023-11-24 04:29 UTC, duidae approved these changes
LGTM

2023-11-24 05:03 UTC, merged