feat(imageResizer): image resizer for Cloud Functions 2nd gen
kids-reporter/kids-reporter-monorepo pull request #378
Opened 2023-11-28 13:51 UTC by howar31

2023-11-29 02:32 UTC, nickhsine commented on packages/image-resizer/README.md
> +- Entry Point: resizeImage
Question:
如果我們要用 Cloud Function，是否要說明怎麼在 local 開發？
畢竟 Cloud Function 預設做了滿多事情的，而這些事情在 local 端並不會發生。

2023-11-29 02:36 UTC, nickhsine reviewed
想順帶問一下，如果我今天修改了程式碼，要部署的話，是修改的工程師要上 Cloud Function 手動上程式碼嗎？

2023-11-29 03:25 UTC, howar31 commented
如討論， Cloud Functions 會幫忙處理 server endpoint 相關的東西
但為了後續維護方便以及開發環境一致性，會修改轉用 Cloud Run

2023-11-30 02:25 UTC, nickhsine reviewed
Suggestion:
Add cloudbuild.yaml to integrate CI/CD.

2023-11-30 02:41 UTC, nickhsine commented on packages/image-resizer/index.js
> +app.use(bodyParser.json())
nitpick:
`app.use(bodyParser.json())` -> `app.use(express.json())`
`express` has `json` method, which is identical to `bodyParser.json`.

2023-11-30 02:41 UTC, nickhsine commented on packages/image-resizer/index.js
> +  const resourceName = event.protoPayload.resourceName
Suggestion: 
use optional chain or add try catch block?
const resourceName = `event?.protoPayload?.resourceName`

2023-11-30 02:41 UTC, nickhsine commented on packages/image-resizer/index.js
> +  const name = resourceName.split('/').slice(5).join('/')
Suggestion:
check `resourceName` is string or not before invoking `.split` function.

2023-11-30 02:41 UTC, nickhsine commented on packages/image-resizer/utils.js
> +  await sendSlackNotification(message)
Question:
Could we only send messages that we need to take care of?

2023-11-30 02:41 UTC, nickhsine commented on packages/image-resizer/index.js
> +    await fs.unlink(tempFilePath)
nitpick:
把 `const tempFilePath = join(tmpdir(), 'tempImage')` 移到判斷照片格式邏輯下方，這樣子是否就不需要
`await fs.unlink(tempFilePath)`？

2023-11-30 02:41 UTC, nickhsine commented on packages/image-resizer/index.js
> +  })
Question:
我們是否要順便把照片改成 webp 檔案格式？

2023-11-30 03:59 UTC, howar31 commented on packages/image-resizer/index.js
> +app.use(bodyParser.json())
done

2023-11-30 03:59 UTC, howar31 commented on packages/image-resizer/index.js
> +  const resourceName = event.protoPayload.resourceName
done

2023-11-30 03:59 UTC, howar31 commented on packages/image-resizer/index.js
> +  const name = resourceName.split('/').slice(5).join('/')
done

2023-11-30 03:59 UTC, howar31 commented on packages/image-resizer/index.js
> +    await fs.unlink(tempFilePath)
done

2023-11-30 03:59 UTC, howar31 commented on packages/image-resizer/utils.js
> +  await sendSlackNotification(message)
We need to discuss what message (log and error) should be sent to Slack

2023-11-30 07:37 UTC, howar31 commented on packages/image-resizer/utils.js
> +  await sendSlackNotification(message)
如討論，Slack 通知只留下:
- 開始壓
- 錯誤

2023-12-05 14:05 UTC, howar31 commented on packages/image-resizer/utils.js
> +  await sendSlackNotification(message)
done

2023-12-05 16:05 UTC, howar31 commented on packages/image-resizer/index.js
> +  })
done

2023-12-08 08:46 UTC, nickhsine requested changes

2023-12-08 08:46 UTC, nickhsine commented on packages/image-resizer/index.js
> +      } (${elapsedTime}s)`
suggestion:
可以參考 `console.time` 和`console.timeEnd` 來處理執行花費的時間？

2023-12-08 08:46 UTC, nickhsine commented on packages/image-resizer/index.js
> +      )}-${Date.now()}-${generateRandomString()}`
Question:
會需要 random string 的原因是我們想要避免檔案名稱相同嗎？

2023-12-08 08:46 UTC, nickhsine commented on packages/image-resizer/index.js
> +  res.status(200).send('ack')
Question:
我們只能回覆 'ack' 當作 response body 嗎？
我想說是不是可以回覆有資訊的訊息，這樣子透過 gcp logging viewer 看 logs 時，可以知道比較多內容。

2023-12-08 08:46 UTC, nickhsine commented on packages/image-resizer/index.js
> +      let sharpPromise
Question:
好奇取名為 `sharpPromise` 的原因？
因為看下方的程式碼， `sharp()` return 的結果不是一個 Promise？

2023-12-09 12:50 UTC, howar31 commented on packages/image-resizer/index.js
> +      )}-${Date.now()}-${generateRandomString()}`
對，當高頻 request 連續進來的時候，若 temp 檔名重複會造成後面壓縮和上傳失敗

2023-12-11 02:58 UTC, howar31 commented on packages/image-resizer/index.js
> +      } (${elapsedTime}s)`
原本是希望把時間資訊跟壓縮結果寫在同一行內，不過使用 `console.time` 可以節省不少 now 的計算

done

2023-12-11 02:58 UTC, howar31 commented on packages/image-resizer/index.js
> +  res.status(200).send('ack')
因為這邊的 ack 只是回給 Eventarc 的 Pub/Sub 而已，並不會出現在 image-resizer 的 log 內，因此沒有產生複雜訊息

2023-12-11 02:58 UTC, howar31 commented on packages/image-resizer/index.js
> +      let sharpPromise
確實 `sharp()` 回傳的不是 promise，後面 `toFile()` 回傳的才是 promise，我誤把兩者混淆了，已修正

renamed

2023-12-11 03:35 UTC, nickhsine approved these changes
LGTM 👍 👍

2023-12-11 04:04 UTC, merged