fix(cms): fix 2fa issue
kids-reporter/kids-reporter-monorepo pull request #675
Opened 2024-10-04 09:24 UTC by duidae

[ticket](https://app.asana.com/0/1205517559975955/1208405635681123/f)

2024-10-07 02:49 UTC, howar31 requested changes

2024-10-07 02:49 UTC, howar31 commented on packages/cms/lists/user.ts
Preview 之前排除在 AllRoles 外 ([ref](https://github.com/kids-reporter/kids-reporter-monorepo/blob/b7f511e5bf4e5084c33c44dec36ebb415475f843/packages/cms/lists/utils/access-control-list.ts#L38))，主要是因為:

1. Preview 有可能是外部使用者使用，此帳號不應該取得任何 CMS 的權限
2. 直接 grant User list 會讓他能透過 graphQL 查詢包含自己以外的任何 User 的資料

建議: 是否有方法可以限制只取得自己的資料，以避免 Preview 在帳密正確後即可透過 graphQL query 獲得 User table 內的資料

2024-10-07 03:52 UTC, duidae commented on packages/cms/lists/user.ts
這樣 call context.prisma 可以略過 keystone 的權限檢查
[https://github.com/kids-reporter/kids-reporter-monorepo/blob/b7f511e5bf4e5084c33c4[…]475f843/packages/cms/express-mini-apps/two-factor-auth/route.ts](https://github.com/kids-reporter/kids-reporter-monorepo/blob/b7f511e5bf4e5084c33c44dec36ebb415475f843/packages/cms/express-mini-apps/two-factor-auth/route.ts#L86)

2024-10-08 08:50 UTC, duidae commented on packages/cms/lists/user.ts
https://github.com/keystonejs/keystone/discussions/7329
在custom admin page, frontend無法使用context去讀db, 故另開一個api endpoint代理bypass讀取

2024-10-08 22:17 UTC, howar31 approved these changes
LGTM

2024-10-09 01:42 UTC, merged